/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom5.gui;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import nhom5.dialog.QuanLySinhVienDialog;
import nhom5.dialog.ThemMonHocDiaLog;
import nhom5.model.GiaoVien;
import nhom5.model.MonHoc;
import nhom5.show.gv.GVMonHocShow;
import nhom5.sql.GiaoVienService;

/**
 *
 * @author Giang Phan
 */
public class GiaoVienUI extends javax.swing.JFrame {
    SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
    private GiaoVien giaoVien;
    DefaultTableModel dtm=null;
    MonHoc monHocSelected=null;
    GiaoVienService giaoVienService=null;
    /**
     * Creates new form GiaoVienUI
     */
    public GiaoVienUI() {
        System.out.println("Hello");
    }
    public GiaoVienUI(GiaoVien gv) {
        this.giaoVien=gv;
        initComponents();
        addControls();
        //addEvents();
        loadList();
        loadDataTable();
    }
    private void loadDataTable(){
        //System.out.println(monHocSelected.getMaMH());
        /*
        ArrayList<GVMonHocShow>dsMH=giaoVienService.dsMonHocTheoMa(giaoVien.getMaGV(), monHocSelected.getMaMH());
        //LOP.MALOP,MAMH,TENMH,NGAYHOC,SOSV
        for(int i=tblQuanLyMonHoc.getRowCount()-1; i>=0; i--){
            dtm.removeRow(i);
        }
        for(GVMonHocShow mh :dsMH){
            Vector<Object>vec=new Vector<>();
            vec.add(mh.getMaLop());
            vec.add(mh.getMaMH());
            vec.add(mh.getTenMH());
            vec.add(mh.getNgayHoc());
            vec.add(mh.getSoSv());
            dtm.addRow(vec);
        }
        */
    }
    private void addEvents(){
        lstMonHoc.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(lstMonHoc.getSelectedValue()==null)
                {
                    return;
                } 
                else{
                    monHocSelected=lstMonHoc.getSelectedValue();
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
                 //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                 //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                 //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent e) {
                 //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    private void addControls(){
        LoginFrm.FrameDragListener frameDragListener = new LoginFrm.FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);
        
        dtm=(DefaultTableModel) tblQuanLyMonHoc.getModel();
        dtm.addColumn("Mã lớp");
        dtm.addColumn("Mã môn");
        dtm.addColumn("Tên môn");
        dtm.addColumn("Ngày dạy");
        dtm.addColumn("Số sv");
        txtTen.setText(giaoVien.getTenGV());
        giaoVienService=new GiaoVienService();
        
    }
    private void loadList(){
        Vector<MonHoc>vec=giaoVienService.dsMonHoc(giaoVien.getMaGV());
        lstMonHoc.setListData(vec);
    }
    public static class FrameDragListener extends MouseAdapter {

        private final JFrame frame;
        private Point mouseDownCompCoords = null;

        public FrameDragListener(JFrame frame) {
            this.frame = frame;
        }

        public void mouseReleased(MouseEvent e) {
            mouseDownCompCoords = null;
        }

        public void mousePressed(MouseEvent e) {
            mouseDownCompCoords = e.getPoint();
        }

        public void mouseDragged(MouseEvent e) {
            Point currCoords = e.getLocationOnScreen();
            frame.setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMonHoc = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuanLyMonHoc = new javax.swing.JTable();
        btnThemMonHoc = new javax.swing.JButton();
        btnQuanLy = new javax.swing.JButton();
        btnThoatGV = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTen = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 134, 222));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý môn học");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("-");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(87, 101, 116));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true), "Danh sách môn học", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 255, 255))); // NOI18N

        lstMonHoc.setBackground(new java.awt.Color(87, 101, 116));
        lstMonHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lstMonHoc.setForeground(new java.awt.Color(255, 255, 255));
        lstMonHoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstMonHoc.setSelectionBackground(new java.awt.Color(10, 189, 227));
        lstMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstMonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstMonHoc);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true), "Chi tiết môn học", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 255, 255))); // NOI18N

        tblQuanLyMonHoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblQuanLyMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblQuanLyMonHoc.setRowHeight(30);
        jScrollPane2.setViewportView(tblQuanLyMonHoc);

        btnThemMonHoc.setBackground(new java.awt.Color(55, 66, 250));
        btnThemMonHoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnThemMonHoc.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom5/gui/add.png"))); // NOI18N
        btnThemMonHoc.setText("Thêm");
        btnThemMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMonHocActionPerformed(evt);
            }
        });

        btnQuanLy.setBackground(new java.awt.Color(113, 88, 226));
        btnQuanLy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom5/gui/manage32.png"))); // NOI18N
        btnQuanLy.setText("Quản lý");
        btnQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyActionPerformed(evt);
            }
        });

        btnThoatGV.setBackground(new java.awt.Color(238, 82, 83));
        btnThoatGV.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnThoatGV.setForeground(new java.awt.Color(255, 255, 255));
        btnThoatGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom5/gui/logout32.png"))); // NOI18N
        btnThoatGV.setText("Thoát");
        btnThoatGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatGVActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(248, 239, 186));
        jLabel4.setText("Xin chào:");

        txtTen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTen.setForeground(new java.awt.Color(27, 156, 252));
        txtTen.setText("Nguyễn Văn Hạnh");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom5/gui/ok24.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(31, 31, 31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThemMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnQuanLy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoatGV, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThoatGV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtTen)))
                        .addGap(57, 57, 57))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnThoatGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatGVActionPerformed
        int cf=JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn thoát?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, new ImageIcon("images/ques.png"));
        if(cf==JOptionPane.YES_OPTION){
            LoginFrm login=new LoginFrm();
            login.setVisible(true);
            login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            login.pack();
            this.dispose();
        }
        else{
            return;
        }
    }//GEN-LAST:event_btnThoatGVActionPerformed

    private void btnThemMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMonHocActionPerformed
        ThemMonHocDiaLog ui=new ThemMonHocDiaLog(giaoVien);
        ui.setVisible(true);
        ui.pack();
    }//GEN-LAST:event_btnThemMonHocActionPerformed

    private void btnQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyActionPerformed
        if(monHocSelected!=null){
            QuanLySinhVienDialog ui=new QuanLySinhVienDialog(giaoVien,monHocSelected.getMaMH());
        ui.setVisible(true);
        }
        else{
            return;
        }
    }//GEN-LAST:event_btnQuanLyActionPerformed

    private void lstMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstMonHocMouseClicked
        
        if(lstMonHoc.getSelectedValue()!=null){
            monHocSelected =lstMonHoc.getSelectedValue();
            ArrayList<GVMonHocShow>dsMH=giaoVienService.dsMonHocTheoMa(giaoVien.getMaGV(), monHocSelected.getMaMH());
        //LOP.MALOP,MAMH,TENMH,NGAYHOC,SOSV
        for(int i=tblQuanLyMonHoc.getRowCount()-1; i>=0; i--){
            dtm.removeRow(i);
        }
        for(GVMonHocShow mh :dsMH){
            Vector<Object>vec=new Vector<>();
            vec.add(mh.getMaLop());
            vec.add(mh.getMaMH());
            vec.add(mh.getTenMH());
            vec.add(sdf.format(mh.getNgayHoc()));
            vec.add(mh.getSoSv());
            dtm.addRow(vec);
        }
        }
        else{
            return;
        }
    }//GEN-LAST:event_lstMonHocMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoVienUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuanLy;
    private javax.swing.JButton btnThemMonHoc;
    private javax.swing.JButton btnThoatGV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<MonHoc> lstMonHoc;
    private javax.swing.JTable tblQuanLyMonHoc;
    private javax.swing.JLabel txtTen;
    // End of variables declaration//GEN-END:variables
}
